Name: Aryan Jha

Program: MBA TECH AI

Cousre: Machine Learning

Topic: Introduction to Machine Learning and Pandas library

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data_frame= pd.read_csv("indian_food.csv") #Reading the file

In [ ]:
data_frame.shape #Getting the rows and column  # 255 instances # 9 features

(255, 9)

In [ ]:
data_frame.size #Getting the rows x column  #Total Cells
#255- No of Indian Dishes
#9- No of features

2295

In [ ]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            255 non-null    object
 1   ingredients     255 non-null    object
 2   diet            255 non-null    object
 3   prep_time       255 non-null    int64
 4   cook_time       255 non-null    int64
 5   flavor_profile  255 non-null    object
 6   course          255 non-null    object
 7   state           255 non-null    object
 8   region          254 non-null    object
dtypes: int64(2), object(7)
memory usage: 18.1+ KB

In [ ]:
data_frame.head

<bound method NDFrame.head of                name                                        ingredients  \
0        Balu shahi                    Maida flour, yogurt, oil, sugar
1            Boondi                            Gram flour, ghee, sugar
2    Gajar ka halwa       Carrots, milk, sugar, ghee, cashews, raisins
3            Ghevar  Flour, ghee, kewra, milk, clarified butter, su...
4       Gulab jamun  Milk powder, plain flour, baking powder, ghee,...
..              ...                                                ...
250       Til Pitha            Glutinous rice, black sesame seeds, gur
251         Bebinca  Coconut milk, egg yolks, clarified butter, all...
252          Shufta  Cottage cheese, dry dates, dried rose petals, ...
253       Mawa Bati  Milk powder, dry fruits, arrowroot powder, all...
254          Pinaca  Brown rice, fennel seeds, grated coconut, blac...

           diet  prep_time  cook_time flavor_profile   course  \
0    vegetarian         45         25          sweet  dessert
1    vegetarian         80         30          sweet  dessert
2    vegetarian         15         60          sweet  dessert
3    vegetarian         15         30          sweet  dessert
4    vegetarian         15         40          sweet  dessert
..          ...        ...        ...            ...      ...
250  vegetarian          5         30          sweet  dessert
251  vegetarian         20         60          sweet  dessert
252  vegetarian         -1         -1          sweet  dessert
253  vegetarian         20         45          sweet  dessert
254  vegetarian         -1         -1          sweet  dessert

               state      region
0        West Bengal        East
1          Rajasthan        West
2             Punjab       North
3          Rajasthan        West
4        West Bengal        East
..               ...         ...
250            Assam  North East
251              Goa        West
252  Jammu & Kashmir       North
253   Madhya Pradesh     Central
254              Goa        West

[255 rows x 9 columns]>

In [ ]:
data_frame.head(5)

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80,30,sweet,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15,60,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15,30,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15,40,sweet,dessert,West Bengal,East

In [ ]:
data_frame.describe()
# Count is the total no. of entries
# Mean, Standard_Deviation,  of all the prep_time and cook_time
# Minimum value: Any instance donot having prep time and cook time is showed by -1

        prep_time   cook_time
count  255.000000  255.000000
mean    31.105882   34.529412
std     72.554409   48.265650
min     -1.000000   -1.000000
25%     10.000000   20.000000
50%     10.000000   30.000000
75%     20.000000   40.000000
max    500.000000  720.000000

In [ ]:
data_frame.isnull()

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
250,False,False,False,False,False,False,False,False,False
251,False,False,False,False,False,False,False,False,False
252,False,False,False,False,False,False,False,False,False
253,False,False,False,False,False,False,False,False,False
254,False,False,False,False,False,False,False,False,False

In [ ]:
data_frame.isnull().sum()

name              0
ingredients       0
diet              0
prep_time         0
cook_time         0
flavor_profile    0
course            0
state             0
region            1
dtype: int64

In [ ]:
data_frame.replace(-1, "Nan")

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80,30,sweet,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15,60,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15,30,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15,40,sweet,dessert,West Bengal,East
...,...,...,...,...,...,...,...,...,...
250,Til Pitha,"Glutinous rice, black sesame seeds, gur",vegetarian,5,30,sweet,dessert,Assam,North East
251,Bebinca,"Coconut milk, egg yolks, clarified butter, all...",vegetarian,20,60,sweet,dessert,Goa,West
252,Shufta,"Cottage cheese, dry dates, dried rose petals, ...",vegetarian,Nan,Nan,sweet,dessert,Jammu & Kashmir,North
253,Mawa Bati,"Milk powder, dry fruits, arrowroot powder, all...",vegetarian,20,45,sweet,dessert,Madhya Pradesh,Central
254,Pinaca,"Brown rice, fennel seeds, grated coconut, blac...",vegetarian,Nan,Nan,sweet,dessert,Goa,West

In [ ]:
# 2 features are Numerical
# 7 features are Categorical

In [ ]:
data_frame.nunique()

name              255
ingredients       252
diet                2
prep_time          22
cook_time          19
flavor_profile      5
course              4
state              25
region              7
dtype: int64


This code seems to be calculating the total time for each recipe by adding the preparation time (prep_time) and the cooking time (cook_time) together. Then, it assigns these total times to a new column named "Total_Time" in the DataFrame data_frame.

In [ ]:
total_time= data_frame.prep_time+data_frame.cook_time
data_frame["Total_Time"]= total_time

In [ ]:
data_frame.head()

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region,Total_Time
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East,70
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80,30,sweet,dessert,Rajasthan,West,110
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15,60,sweet,dessert,Punjab,North,75
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15,30,sweet,dessert,Rajasthan,West,45
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15,40,sweet,dessert,West Bengal,East,55

This code defines a function named Ingredient_count which takes a string x as input. Within the function, the string x is split into a list of ingredients based on commas, and this list is returned.

In [ ]:
def Ingredient_count(x):
  Total_Ingredients= x.split(",")
  return(Total_Ingredients)
  data_frame["No of ingredients"]= data_frame.ingredients.apply(lambda x:Ingredient_count(x))

In [ ]:
data_frame.head()

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region,Total_Time
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East,70
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80,30,sweet,dessert,Rajasthan,West,110
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15,60,sweet,dessert,Punjab,North,75
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15,30,sweet,dessert,Rajasthan,West,45
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15,40,sweet,dessert,West Bengal,East,55